#!/bin/sh
(                        python3.8 t_fthmc_0.py > t_fthmc_0cpu1_N.log 2>&1 )
( TF_DETERMINISTIC_OPS=1 python3.8 t_fthmc_0.py > t_fthmc_0cpu1_D.log 2>&1 )
(                        python3.8 t_fthmc_1.py > t_fthmc_1cpu1_N.log 2>&1 )
( TF_DETERMINISTIC_OPS=1 python3.8 t_fthmc_1.py > t_fthmc_1cpu1_D.log 2>&1 )
