#!/bin/sh
(                        python3.8 t_fthmc_0_iop2.py > t_fthmc_0_iop2cpu1_N.log 2>&1 )
( TF_DETERMINISTIC_OPS=1 python3.8 t_fthmc_0_iop2.py > t_fthmc_0_iop2cpu1_D.log 2>&1 )
(                        python3.8 t_fthmc_1_iop2.py > t_fthmc_1_iop2cpu1_N.log 2>&1 )
( TF_DETERMINISTIC_OPS=1 python3.8 t_fthmc_1_iop2.py > t_fthmc_1_iop2cpu1_D.log 2>&1 )
